spring:
  file:
    uploadPath: /Users/kimyoungjae/desktop/myproject
    url: http://localhost:8080/api/v1/admin/file/show/image
  datasource:
    url: jdbc:mysql://158.179.163.36:3306/account?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: backend
    password: master1234!@#$
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
        format_sql: true
        show_sql: true
  data:
    redis:
      host: 158.179.163.36
      port: 6379
      password: back1234!@#$
admin:
  apiKeyName: stakingAdmin
  aesKey: VSQCuA9a9IiCK3gRPiV8hiXJVgje058e
  aesIv: OWrduHXwgprh6Vbp
jwt:
  secretKey: testKeyNameisExample2023