spring:
  datasource:
    url: jdbc:mysql://<host>:<port>/<database>?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <username>
    password: <password>
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: none
        format_sql: true
        show_sql: true
  data:
    redis:
      host: <host>
      port: 123
      password: <password>
  file:
    uploadPath: <uploadPath>
    url: <url>

jwt:
  secretKey: <secretKey>

admin:
  apiKeyName: <apiKeyName>
  aesKey: <aesKey>
  aesIv: <aesIv>