spring:
  datasource:
    url: jdbc:mysql://158.179.163.36:3306/account?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: backend
    password: master1234!@#$
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update
        format_sql: true
        show_sql: true
  data:
    redis:
      host: 158.179.163.36
      port: 6379
      password: back1234!@#$
jwt:
  secretKey: testKeyNameisExample2023
